version: '3.4'

services:
  despesas-frontend-angular:
    image: alexfariakof/despesas-frontend-angular-img
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
