#stage 1
FROM node:21-slim as node
WORKDIR /app
COPY . .
RUN npm install -g npm@latest
RUN npm install
RUN npm run build --prod
#stage 2
EXPOSE 80
FROM nginx:alpine
COPY --from=node /app/dist/despesas-frontend-angular /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
