version: '3.4'
services:
  despesas-frontend-angular-prod:
    container_name: prod
    image: alexfariakof/despesas-frontend-angular-img
    build:
      context: .
      dockerfile: ./Dockerfile-Production
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
