version: '3.4'
services:
  despesas-angular-dev:
    container_name: despesas-angular-dev
    image: despesas-angular-dev-img
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 9229:9229
    volumes:
      - ./:/app
    command: |
      /bin/sh -c "npm install --silent --no-audit --no-fund; npm start;"
