# actions-common/install-dependencies.yml
name: 'Install Dependencies'
description: 'Install npm dependencies'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        npm install npm@latest
        npm install -g @angular/cli
        npm install
      continue-on-error: false
