name: Build And Test
on:
  workflow_call:
  push:
    branches:
      - master
      - develop

  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Node.js Ver. 21
        uses: actions/setup-node@v3
        with:
          node-version: '21.*.*'

      - name: Install dependencies
        run: |
          npm install -g @angular/core @angular/cli > /dev/null 2>&1
          npm install
        continue-on-error: false

      - name: Build
        run: ng build
        continue-on-error: false

      - name: Test
        run: npm run test
        continue-on-error: false

  trigger_tests_sonarcloud:
    needs: build_and_test
    name: Test and Analysis Code In Sonar Cloud
    uses: alexfariakof/angular-frontend-despesas/.github/workflows/tests_In_Sonar_Cloud.yml@master
    secrets: inherit
