name: Test Trigger Workflow End-to-End
on:
  workflow_run:
    workflows: ["Run Build and Tests"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      e2e_test_input:
        description: 'Trigger Workflow End-to-End'
        required: true

  push:
    branches:
      - feature/Create-workflow-to-trigger-e2e-tests

jobs:
  trigger_e2e_tests:
    name: Trigger Run End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        run: |
            const { Octokit } = require("@octokit/core");
            const octokit = new Octokit({
              auth: process.env.GITHUB_TOKEN
            });

            const response = await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: process.env.GITHUB_REPOSITORY_OWNER,
              repo: process.env.GITHUB_REPOSITORY,
              workflow_id: 'YOUR-WORKFLOW-ID',
              ref: ${{ github.workflow_ref }},
              inputs: {
                e2e_test_input: 'run'
              },
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
            console.log(response);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
