name: Test Trigger Workflow End-to-End
on:
  push:
    branches:
      - feature/Create-workflow-to-trigger-e2e-tests

jobs:
  trigger_e2e_tests:
    name: Trigger Run End-to-End Tests
    uses: alexfariakof/despesas-frontend-angular/.github/workflows/Tests_e2e.yml@master
