name: Run Tests e2e
on:
  #workflow_run:
    #workflows: Deploy Development Project
    #types:
     # - completed
  push:
    branches:
      - feature/Create-workflow-to-trigger-e2e-tests

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - pre-release
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        id: trigger
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.TRIGGER_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/alexfariakof/despesas-frontend-angular-tests-e2e/dispatches \
            -d '{"event_type":"trigger-python-plyawright-e2e-tests", "client_payload": {"unit": false, "integration": true, "father_workflow_id": "${{ github.run_id }}" }}'

      - name: Wait 15s To Workflow Initialize
        run: sleep 30

      - name: Download Workflow Run ID
        uses: actions/download-artifact@v2
        with:
          name: run_id-${{ github.run_id }}
          path: run_id-${{ github.run_id }}.txt

      - name: Set Workflow Run ID
        run: |
          run_id=$(cat run_id-${{ github.run_id }}.txt)
          echo "Workflow Run ID: $run_id"

      - name: Wait for Triggered Workflow Test e2e
        run: |
          echo "Workflow Triggered Id : $workflow_id"
          response=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/alexfariakof/despesas-frontend-angular-tests-e2e/actions/runs/$workflow_id")

          echo $response
          status=$(echo $response | jq -r '.status')
          conclusion=$(echo $response | jq -r '.conclusion')

          if [ "$status" == "completed" ] && [ "$conclusion" == "success" ]; then
            echo "workflow_status=${{ job.status }}" >> $GITHUB_OUTPUT
          else
            echo "workflow_status=failure" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
