name: Run Tests e2e
on:
  #workflow_run:
    #workflows: Deploy Development Project
    #types:
     # - completed
  push:
    branches:
      - feature/Create-workflow-to-trigger-e2e-tests

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - pre-release

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/alexfariakof/despesas-frontend-angular-tests-e2e/dispatches \
          -d '{"event-type":"trigger-python-plyawright-e2e-tests"}'
