name: Run Tests e2e
on:
  #workflow_run:
    #workflows: Deploy Development Project
    #types:
     # - completed
  push:
    branches:
      - feature/Create-workflow-to-trigger-e2e-tests

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - pre-release

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-python-tests
