name: Run Tests e2e
on:
  #workflow_run:
    #workflows: Deploy Development Project
    #types:
     # - completed
  push:
    branches:
      - feature/Create-workflow-to-trigger-e2e-tests

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - pre-release

jobs:
  trigger:
    runs-on: ubuntu-latest
    outputs:
      workflow_status: ${{ steps.trigger.outputs.workflow_status }}
    steps:
      - name: Trigger Workflow
        id: trigger
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/alexfariakof/despesas-frontend-angular-tests-e2e/dispatches \
          -d '{"event_type":"trigger-python-plyawright-e2e-tests", "client_payload": {
            "workflow_run_id": "${{ github.run_id }}"
          }}'

      - name: Wait for Triggered Workflow Test e2e
        uses: actions/github-script@v4
        with:
          script: |
            const { data: workflowRun } = await github.actions.getWorkflowRun({
              owner: 'alexfariakof',
              repo: 'despesas-frontend-angular-tests-e2e',
              run_id: "${{ github.run_id }}"
              token: "${{ secrets.WORKFLOW_TRIGGER_TOKEN }}"
            });

            if (workflowRun.status === 'completed' && workflowRun.conclusion === 'success') {
                core.setOutput('workflow_status', 'success');
            } else {
                core.setOutput('workflow_status', 'failure');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
