name: Run Tests e2e
on:
  #workflow_run:
    #workflows: Deploy Development Project
    #types:
     # - completed
  push:
    branches:
      - feature/Create-workflow-to-trigger-e2e-tests

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - pre-release

jobs:
  run_tests_e2e:
    name: Run Tests e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Executar o Workflow Externo
        uses: softprops/action-gh-run@v1
        with:
          repo: alexfariakof/despesas-frontend-angular-tests-e2e
          workflow: main.yml
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
